### ISSUE TITLE
compile erros

### ISSUE THREAD

**Issue by yifanend** [ultraembedded/riscv#2]
Hi,I got the code and compile,but get errors as flow:

g++ -fpic -O2 -I./ -I./verilated -I../../isa_sim -I/usr/share/verilator/include -I/usr/share/verilator/include/vltstd -I/usr/local/systemc_2.3.3/include -DVM_TRACE=1 -c main.cpp -o obj/main.o
In file included from main.cpp:2:0:
testbench.h: In member function ‘virtual void testbench::write(uint32_t, uint8_t)’:
testbench.h:109:23: error: ‘struct Vriscv_tcm_top’ has no member named ‘v’
         m_dut->m_rtl->v->u_mem_tcm->write(addr, data);
                       ^
testbench.h: In member function ‘virtual uint8_t testbench::read(uint32_t)’:
testbench.h:116:30: error: ‘struct Vriscv_tcm_top’ has no member named ‘v’
         return m_dut->m_rtl->v->u_mem_tcm->read(addr);
                              ^

**Comment by yifanend** [comment]
return m_dut->m_rtl->v->u_mem_tcm  should be return m_dut->m_rtl->riscv_tcm_top->u_mem_tcm

**Comment by yifanend** [comment]
now got this error:

g++ -O2 -L/usr/local/systemc_2.3.3/lib-linux64  -L./lib -L../../isa_sim obj/riscv_tcm_top_rtl.o obj/main.o -o build/test.x -lsystemc -lisa_sim -lsyscverilated -lelf -lbfd
/usr/bin/ld: build/test.x: hidden symbol `bfd_check_format_matches' in /usr/lib64/libbfd.a(format.o) is referenced by DSO
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make[1]: *** [build/test.x] Error 1
make[1]: Leaving directory `/root/work/risc_v/riscv-master/top_tcm_axi/tb'
make: *** [build] Error 2

**Comment by ultraembedded** [comment]
> return m_dut->m_rtl->v->u_mem_tcm should be return m_dut->m_rtl->riscv_tcm_top->u_mem_tcm

Hi,

It depends on the version of verilator. On older versions it is member 'v', and new versions it is 'module_name'!

**Comment by ultraembedded** [comment]
> now got this error:
> 
> g++ -O2 -L/usr/local/systemc_2.3.3/lib-linux64 -L./lib -L../../isa_sim obj/riscv_tcm_top_rtl.o obj/main.o -o build/test.x -lsystemc -lisa_sim -lsyscverilated -lelf -lbfd
> /usr/bin/ld: build/test.x: hidden symbol `bfd_check_format_matches' in /usr/lib64/libbfd.a(format.o) is referenced by DSO /usr/bin/ld: final link failed: Bad value collect2: error: ld returned 1 exit status make[1]: *** [build/test.x] Error 1 make[1]: Leaving directory `/root/work/risc_v/riscv-master/top_tcm_axi/tb'
> make: *** [build] Error 2

I'm not sure what is going on here - I would guess you have multiple incompatible bfd versions present.

**Comment by yifanend** [comment]
> now got this error:
> g++ -O2 -L/usr/local/systemc_2.3.3/lib-linux64 -L./lib -L../../isa_sim obj/riscv_tcm_top_rtl.o obj/main.o -o build/test.x -lsystemc -lisa_sim -lsyscverilated -lelf -lbfd
> /usr/bin/ld: build/test.x: hidden symbol bfd_check_format_matches' in /usr/lib64/libbfd.a(format.o) is referenced by DSO /usr/bin/ld: final link failed: Bad value collect2: error: ld returned 1 exit status make[1]: *** [build/test.x] Error 1 make[1]: Leaving directory /root/work/risc_v/riscv-master/top_tcm_axi/tb'
> make: *** [build] Error 2
> 
> I'm not sure what is going on here - I would guess you have multiple incompatible bfd versions present.

bfd_check_format_matches  has "hidden"  attribute in libbfd.a, so linker will link to libbfd.so.
libbfd.a's "objdump -t " info like this:
 
0000000000000000 l    d  .note.GNU-stack        0000000000000000 .note.GNU-stack
0000000000000000 l    d  .eh_frame      0000000000000000 .eh_frame
0000000000000000 g     F .text  0000000000000908 **.hidden** bfd_check_format_matches
0000000000000000         *UND*  0000000000000000 _GLOBAL_OFFSET_TABLE_
0000000000000000         *UND*  0000000000000000 _bfd_target_vector_entries

i download  the binutils-2.27 source code and edit ./bfd/bfd-in2.h  (line 7556)
from 
bfd_boolean bfd_check_format_matches
   (bfd *abfd, bfd_format format, char ***matching);
to
**__attribute__((visibility ("default")))** bfd_boolean bfd_check_format_matches
   (bfd *abfd, bfd_format format, char ***matching);

then copile binutils and replace /usr/local/lib64/libbfd.a with the new libbfd.a. after this operations the linker could work.

wish this would be useful for someone.Could you give the dependancies's version? @ultraembedded

**Comment by ultraembedded** [comment]
I have removed the call to bfd_check_format_matches which is not strictly necessary.
This should avoid the dependence on BFD version.
