### ISSUE TITLE
Run $make under top_tcm_axi/tb/

### ISSUE THREAD

**Issue by alan-chen1412** [ultraembedded/riscv#8]
hello, I try to run the makefile under top_tcm_axi/tb, but got some error as follow:

In file included from main.cpp:2:
testbench.h: In member function ‘virtual void testbench::write(uint32_t, uint8_t)’:
testbench.h:111:23: error: ‘struct Vriscv_tcm_top’ has no member named ‘__VlSymsp’; did you mean ‘Vriscv_tcm_top__Syms* const Vriscv_tcm_top::vlSymsp’? (not accessible from this context)
  111 |         m_dut->m_rtl->__VlSymsp->TOP__v__u_tcm.write(addr, data);
      |                       ^~~~~~~~~
In file included from testbench.h:12,
                 from main.cpp:2:
./verilated/Vriscv_tcm_top.h:26:33: note: declared private here
   26 |     Vriscv_tcm_top__Syms* const vlSymsp;
      |                                 ^~~~~~~
In file included from main.cpp:2:
testbench.h: In member function ‘virtual uint8_t testbench::read(uint32_t)’:
testbench.h:127:30: error: ‘struct Vriscv_tcm_top’ has no member named ‘__VlSymsp’; did you mean ‘Vriscv_tcm_top__Syms* const Vriscv_tcm_top::vlSymsp’? (not accessible from this context)
  127 |         return m_dut->m_rtl->__VlSymsp->TOP__v__u_tcm.read(addr);
      |                              ^~~~~~~~~
In file included from testbench.h:12,
                 from main.cpp:2:
./verilated/Vriscv_tcm_top.h:26:33: note: declared private here
   26 |     Vriscv_tcm_top__Syms* const vlSymsp;
      |                                 ^~~~~~~
In file included from main.cpp:2:
testbench.h: In member function ‘virtual uint32_t testbench::get_opcode()’:
testbench.h:158:37: warning: no return statement in function returning non-void [-Wreturn-type]
  158 |     uint32_t  get_opcode(void)    { }
      |                                     ^
make[1]: *** [makefile.build_sysc_tb:56: obj/main.o] Error 1
make[1]: Leaving directory '/home/alan/riscv/top_tcm_axi/tb'
make: *** [makefile:30: build] Error 2
---------------------------------Briefly speaking--------------------------------------
The main error message is : 
testbench.h:111:23: error: ‘struct Vriscv_tcm_top’ has no member named ‘__VlSymsp’; did you mean ‘Vriscv_tcm_top__Syms* const Vriscv_tcm_top::vlSymsp’? (not accessible from this context)
  111 |         m_dut->m_rtl->__VlSymsp->TOP__v__u_tcm.write(addr, data);

I try to use replace __VlSymsp with vlSymsp but got error said "vlSymsp is private"
I am wondering if it is caused by the different version of verilator?

Could anyone help me with this error?

**Comment by Tamnac** [comment]
Hi did you figure out to fix this? I'm running in to the same issue
